import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'package:atmos_trs_system/config/supabase_report_templates_config.dart';
import 'package:atmos_trs_system/utils/dot_report_preview.dart';

/// Builds a printable PDF from the same preview table used in Analytics.
Future<Uint8List> buildDotReportPdfBytes({
  required DotFormCatalogEntry form,
  required DotReportPreviewTable preview,
  required String scopeLabel,
  required DateTime startDate,
  required DateTime endDate,
}) async {
  final doc = pw.Document();
  final dateLine =
      '${startDate.year}-${startDate.month.toString().padLeft(2, '0')}-${startDate.day.toString().padLeft(2, '0')}'
      ' → '
      '${endDate.year}-${endDate.month.toString().padLeft(2, '0')}-${endDate.day.toString().padLeft(2, '0')}';

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4.landscape,
      margin: const pw.EdgeInsets.all(28),
      build: (context) => [
        pw.Text(
          form.displayLabel,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          '$scopeLabel · $dateLine',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          preview.summaryLine,
          style: const pw.TextStyle(fontSize: 10),
        ),
        pw.SizedBox(height: 14),
        if (preview.rows.isEmpty)
          pw.Text(
            'No data rows for this range. Gaps below explain what ATMOS still needs.',
            style: const pw.TextStyle(fontSize: 11),
          )
        else
          pw.TableHelper.fromTextArray(
            headers: preview.headers,
            data: [
              ...preview.rows,
              if (preview.footer != null) preview.footer!,
            ],
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 9,
            ),
            cellStyle: const pw.TextStyle(fontSize: 8.5),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            cellAlignment: pw.Alignment.centerLeft,
            border: pw.TableBorder.all(color: PdfColors.grey600, width: 0.4),
          ),
        if (preview.gaps.isNotEmpty) ...[
          pw.SizedBox(height: 16),
          pw.Text(
            'ATMOS gaps',
            style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 6),
          for (final g in preview.gaps)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 3),
              child: pw.Text('• $g', style: const pw.TextStyle(fontSize: 9)),
            ),
        ],
        pw.SizedBox(height: 18),
        pw.Text(
          'Generated by ATMOS TRS — best-effort fill from current data. '
          'Not a blank official template.',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
        ),
      ],
    ),
  );

  return doc.save();
}

String dotReportPdfFilename({
  required DotFormCatalogEntry form,
  required String scopeSlug,
  required DateTime startDate,
  required DateTime endDate,
}) {
  final s =
      '${startDate.year}${startDate.month.toString().padLeft(2, '0')}${startDate.day.toString().padLeft(2, '0')}';
  final e =
      '${endDate.year}${endDate.month.toString().padLeft(2, '0')}${endDate.day.toString().padLeft(2, '0')}';
  final slug = scopeSlug.trim().isEmpty ? 'report' : scopeSlug.trim();
  return 'ATMOS_${form.id}_${slug}_${s}_$e.pdf';
}
